# Generated by Django 3.0.5 on 2021-05-17 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('rider', models.CharField(max_length=30)),
                ('currentlocation', models.CharField(max_length=45)),
                ('destination', models.CharField(max_length=45)),
                ('lata', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longa', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latb', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longb', models.DecimalField(decimal_places=6, max_digits=10)),
                ('driver', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('address', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('total_balance', models.DecimalField(
                    decimal_places=1, max_digits=5)),
                ('overdue', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 primary_key=True, serialize=False, to='CM.User')),
                ('plateNum', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('currentlocation', models.CharField(max_length=45, null=True)),
                ('destination', models.CharField(max_length=45, null=True)),
                ('lata', models.DecimalField(
                    decimal_places=6, max_digits=10, null=True)),
                ('longa', models.DecimalField(
                    decimal_places=6, max_digits=10, null=True)),
                ('latb', models.DecimalField(
                    decimal_places=6, max_digits=10, null=True)),
                ('longb', models.DecimalField(
                    decimal_places=6, max_digits=10, null=True)),
            ],
        ),
    ]
