# Generated by Django 3.0.5 on 2021-04-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('address', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('total_balance', models.DecimalField(decimal_places=1, max_digits=5)),
                ('overdue', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
