# Generated by Django 3.0.5 on 2021-06-11 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('rider', models.CharField(max_length=30)),
                ('currentlocation', models.CharField(max_length=45)),
                ('destination', models.CharField(max_length=45)),
                ('lata', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longa', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latb', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longb', models.DecimalField(decimal_places=6, max_digits=10)),
                ('driver', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                 help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True)),
                ('rating', models.DecimalField(
                    blank=True, decimal_places=1, max_digits=2)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('total_balance', models.DecimalField(
                    blank=True, decimal_places=1, max_digits=5)),
                ('overdue', models.DecimalField(
                    blank=True, decimal_places=1, max_digits=5)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                 related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.',
                 related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('plateNum', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('currentlocation', models.CharField(max_length=45, null=True)),
                ('destination', models.CharField(max_length=45, null=True)),
                ('lata', models.DecimalField(
                    decimal_places=6, max_digits=10, null=True)),
                ('longa', models.DecimalField(
                    decimal_places=6, max_digits=10, null=True)),
                ('latb', models.DecimalField(
                    decimal_places=6, max_digits=10, null=True)),
                ('longb', models.DecimalField(
                    decimal_places=6, max_digits=10, null=True)),
            ],
        ),

    ]
