# Generated by Django 3.0.5 on 2021-04-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateNum', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CM.User')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('xcoordinate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('ycoordinate', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CM.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('pickup', models.CharField(max_length=50)),
                ('passengercount', models.IntegerField()),
                ('totalFare', models.DecimalField(decimal_places=1, max_digits=5)),
                ('dropoff', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CM.Driver')),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CM.Location')),
                ('passengers', models.ManyToManyField(to='CM.User')),
            ],
        ),
    ]
