# Generated by Django 3.0.5 on 2021-06-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
