# Generated by Django 3.0.5 on 2021-04-08 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0002_driver_location_ride_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CM.User'),
        ),
    ]
