# Generated by Django 3.0.5 on 2021-05-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0002_auto_20210517_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='ipaddr',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='ipaddr',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
