# Generated by Django 3.0.5 on 2021-06-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0003_auto_20210612_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='lata',
            field=models.DecimalField(decimal_places=20, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='latb',
            field=models.DecimalField(decimal_places=20, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='longa',
            field=models.DecimalField(decimal_places=20, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='longb',
            field=models.DecimalField(decimal_places=20, max_digits=50, null=True),
        ),
    ]
