# Generated by Django 3.0.5 on 2021-06-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0003_auto_20210524_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
